project:
  type: website
  output-dir: docs


website:
  title: "fhb-prediction-model"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "Anthesis Date Estimation"
      - href: weather_data.qmd
        text: "Weather Data Script"
      - href: Functional data analysis.qmd
        text: "Functional data analysis"
      - href: logistic_models2.qmd
        text: "Logistic and Ensemble Models"
      - href: logistic_models.qmd
        text: "Net Monetary Benefit (NMB) Analysis"
      - href: figures.qmd
        text: "Figures"
      - href: map.qmd
        text: "Map"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

